import mysql.connector #import libraries
import smtplib #sending function
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart


mydb = mysql.connector.connect( # Connection to database
  host="localhost", # your host, usually localhost
  db="fltechnicsif", #database name
  user="root",  # your username
  passwd="irina" # your password
)
 # Creating request for aircraft from EU

mycursor = mydb.cursor() #  initialize cursor for execute all the queries 

# Use the SQL request
mycursor.execute("SELECT aircraft.TAIL_NUMBER, model.MODEL_NUMBER, model.DESCRIPTION, aircraft.CMP_OWNER, country_codes.code, country_codes.COUNTRY_NAME FROM aircraft JOIN companies ON aircraft.CMP_OWNER=companies.CMP_AUTO_KEY JOIN country_codes ON companies.COC_AUTO_KEY=country_codes.COC_AUTO_KEY JOIN model ON aircraft.MDL_AUTO_KEY=model.MDL_AUTO_KEY WHERE country_codes.SDF_COC_003 = 'T';")

aircraft_from_eu = "" # tables forming

for x in mycursor: # loop for iterating over a sequence
    # table forming
    aircraft_from_eu += '<tr>' + '<td>' + x[0] + '</td>' + '<td>' + x[1] + '</td>' + '<td>' + x[2] + '</td>'  + '<td>' + x[3] + '</td>'  + '<td>' + x[4] + '</td>'  + '<td>' + x[5] + '</td>' + '</tr>'

mycursor.close()

# Creating request for aircraft not from EU
mycursor = mydb.cursor()

mycursor.execute("SELECT aircraft.TAIL_NUMBER, model.MODEL_NUMBER, model.DESCRIPTION, aircraft.CMP_OWNER, country_codes.code, country_codes.COUNTRY_NAME FROM aircraft JOIN companies ON aircraft.CMP_OWNER=companies.CMP_AUTO_KEY JOIN country_codes ON companies.COC_AUTO_KEY=country_codes.COC_AUTO_KEY JOIN model ON aircraft.MDL_AUTO_KEY=model.MDL_AUTO_KEY WHERE country_codes.SDF_COC_003 = 'F';")

aircraft_from_not_eu = ""

for x in mycursor:
    
    aircraft_from_not_eu += '<tr>' + '<td>' + x[0] + '</td>' + '<td>' + x[1] + '</td>' + '<td>' + x[2] + '</td>'  + '<td>' + x[3] + '</td>'  + '<td>' + x[4] + '</td>'  + '<td>' + x[5] + '</td>' + '</tr>'

mycursor.close()

#Sending emails with HTML content
port = 2525
smtp_server = "smtp.mailtrap.io"
login = "fd3844bf664da9" # paste your login generated by Mailtrap
password = "ab3e898b9c6cd2" # paste your password generated by Mailtrap
 
sender_email = "irinka.fedotova@gmail.com"
receiver_email = "demo@fltechnics.com"
message = MIMEMultipart("alternative")
message["Subject"] = "multipart test"
message["From"] = sender_email
message["To"] = receiver_email
 
# write the HTML part
html = """\
<!DOCTYPE html>
<html>
<head>
</head>
<body>

<h2>Aircrafts list</h2>

<table>
  
  <tr>
    <th>Aircrafts belong EU</th>
    <th>Aircraft not belong to EU</th>
  </tr>
  <tr>
    <td>""" + """<table border='1', bgcolor="#83c3f6">
    <thead>
    <tr>
      <th>TAIL_NUMBER</th>
      <th>MODEL_NUMBER</th>
      <th>DESCRIPTION</th>
      <th>CMP_OWNER</th>
      <th>COUNTRY_CODE</th>
      <th>COUNTRY_NAME</th>
    </tr>
    </thead>

      <tbody>""" + aircraft_from_eu + """</tbody>
      </table>
     </td>
    <td>
    <table border='1' bgcolor="#fa6767">
    <thead>
    <tr>
      <th>TAIL_NUMBER</th>
       <th>MODEL_NUMBER</th>
       <th>DESCRIPTION</th>
       <th>CMP_OWNER</th>
       <th>COUNTRY_CODE</th>
       <th>COUNTRY_NAME</th>
      </tr></thead>
      <tbody>""" + aircraft_from_not_eu + """</tbody>
      </table>
     </td>
  </tr>
 </table>
</body>
</html>
"""

# Record the MIME types of part - text/html.

msg_html = MIMEText(html, 'html')

# convert both parts to MIMEText objects and add them to the MIMEMultipart message
part = MIMEText(html, "html")

message.attach(part)
 
# send your email
with smtplib.SMTP("smtp.mailtrap.io", 2525) as server:
    server.login(login, password)
    server.sendmail(
        sender_email, receiver_email, message.as_string()
    )
print('sent') 
